package portability

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// GenerateArtifacts 由 Contract 产生可复现的开发者产物。
// 输出顺序固定、不含时间戳与环境路径，因此同一 Applied Model 重复生成必须字节一致。
type GeneratedArtifacts struct {
	ContractJSON   []byte
	ClientTypeScript []byte
}

// GenerateArtifacts 产生 application-api.json 与 modelry-client.ts 的内容。
func GenerateArtifacts(contract ApplicationAPIContract) (GeneratedArtifacts, error) {
	canonical := contract
	collections := append([]ContractCollection(nil), contract.Collections...)
	sort.SliceStable(collections, func(left, right int) bool { return collections[left].Name < collections[right].Name })
	for index := range collections {
		rules := append([]ContractAccessRule(nil), collections[index].AccessRules...)
		sort.SliceStable(rules, func(left, right int) bool { return rules[left].Operation < rules[right].Operation })
		collections[index].AccessRules = rules
		fields := append([]canonicalField(nil), collections[index].Fields...)
		sort.SliceStable(fields, func(left, right int) bool { return fields[left].Name < fields[right].Name })
		collections[index].Fields = fields
		endpoints := append([]string(nil), collections[index].Endpoints...)
		sort.Strings(endpoints)
		collections[index].Endpoints = endpoints
	}
	canonical.Collections = collections

	document := struct {
		Version     string               `json:"version"`
		ContentHash string               `json:"contentHash"`
		APIBasePath string               `json:"apiBasePath"`
		Collections []ContractCollection `json:"collections"`
	}{Version: canonical.Version, ContentHash: canonical.ContentHash, APIBasePath: canonical.APIBasePath, Collections: collections}
	encoded, err := json.MarshalIndent(document, "", "  ")
	if err != nil {
		return GeneratedArtifacts{}, fmt.Errorf("%w: encode generated contract: %v", ErrStorage, err)
	}
	encoded = append(encoded, '\n')
	return GeneratedArtifacts{ContractJSON: encoded, ClientTypeScript: renderClient(document.Version, document.ContentHash, collections)}, nil
}

func renderClient(version, contentHash string, collections []ContractCollection) []byte {
	builder := &bytes.Buffer{}
	builder.WriteString("// Generated by Modelry. Do not edit.\n")
	builder.WriteString("// Runtime version: " + version + "\n")
	builder.WriteString("// Contract hash: " + contentHash + "\n")
	builder.WriteString("// This client calls the canonical Application API only; Access Rules, Sessions, Secrets, and Audit are unchanged.\n\n")
	builder.WriteString("export const apiBasePath = '/api/v1';\n")
	builder.WriteString("export const contractHash = '" + contentHash + "';\n\n")
	builder.WriteString("export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };\n\n")
	for _, collection := range collections {
		builder.WriteString(collectionInterface(collection))
	}
	builder.WriteString("export type ModelryClientOptions = { baseUrl?: string; fetchImpl?: typeof fetch; sessionToken?: string };\n\n")
	builder.WriteString(clientRuntime)
	for _, collection := range collections {
		builder.WriteString(clientCollectionMethods(collection.Name))
	}
	builder.WriteString("  };\n}\n")
	return builder.Bytes()
}

const clientRuntime = `export function createModelryClient(options: ModelryClientOptions = {}) {
  const baseUrl = (options.baseUrl ?? '').replace(/\/$/, '');
  const call = async (method, path, body) => {
    const headers = { Accept: 'application/json' };
    if (body !== undefined) headers['Content-Type'] = 'application/json';
    if (options.sessionToken) headers.Authorization = 'Bearer ' + options.sessionToken;
    const response = await (options.fetchImpl ?? fetch)(baseUrl + path, {
      method,
      headers,
      cache: 'no-store',
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    if (!response.ok) throw new Error('Modelry request failed with ' + response.status);
    if (response.status === 204) return undefined;
    return await response.json();
  };
  return {
    contractHash,
    apiBasePath,
`

// clientCollectionMethods 为一个 Collection 生成类型安全的方法组合。
func clientCollectionMethods(name string) string {
	identifier := tsIdentifier(name)
	endpoint := collectionEndpoint(name)
	builder := &bytes.Buffer{}
	builder.WriteString("    " + identifier + ": {\n")
	builder.WriteString("      list: () => call('GET', '" + endpoint + "'),\n")
	builder.WriteString("      create: (values: " + identifier + "Values) => call('POST', '" + endpoint + "', { values }),\n")
	builder.WriteString("      get: (recordId: string) => call('GET', '" + endpoint + "/' + encodeURIComponent(recordId)),\n")
	builder.WriteString("      update: (recordId: string, values: Partial<" + identifier + "Values>) => call('PATCH', '" + endpoint + "/' + encodeURIComponent(recordId), { values }),\n")
	builder.WriteString("      remove: (recordId: string) => call('DELETE', '" + endpoint + "/' + encodeURIComponent(recordId)),\n")
	builder.WriteString("    },\n")
	return builder.String()
}
func collectionEndpoint(name string) string {
	return "/api/v1/" + name
}

func collectionInterface(collection ContractCollection) string {
	identifier := tsIdentifier(collection.Name)
	builder := &bytes.Buffer{}
	builder.WriteString("/** " + collection.Name + " (" + collection.Type + ") · schema version " + fmt.Sprint(collection.SchemaVersion) + " */\n")
	builder.WriteString("export type " + identifier + "Values = {\n")
	for _, field := range collection.Fields {
		builder.WriteString("  " + tsProperty(field.Name) + ": " + tsType(field) + ";\n")
	}
	builder.WriteString("};\n\n")
	builder.WriteString("export type " + identifier + "Record = " + identifier + "Values & { id: string };\n\n")
	builder.WriteString("export type " + identifier + "AccessRules = {\n")
	for _, rule := range collection.AccessRules {
		builder.WriteString("  " + tsProperty(rule.Operation) + ": '" + rule.Mode + "';\n")
	}
	builder.WriteString("};\n\n")
	return builder.String()
}

func tsType(field canonicalField) string {
	base := "JsonValue"
	switch field.Type {
	case "text", "dateTime":
		base = "string"
	case "number":
		base = "number"
	case "boolean":
		base = "boolean"
	case "json":
		base = "JsonValue"
	case "relation":
		base = "string"
	case "file":
		base = "string"
	case "files":
		base = "string[]"
	}
	if !field.Required {
		base += " | null"
	}
	return base
}

func tsIdentifier(name string) string {
	parts := splitIdentifier(name)
	builder := &strings.Builder{}
	for _, part := range parts {
		builder.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	if builder.Len() == 0 {
		return "Collection"
	}
	return builder.String()
}

func tsProperty(name string) string {
	if isSimpleIdentifier(name) {
		return name
	}
	return "'" + strings.ReplaceAll(name, "'", "\\'") + "'"
}

func isSimpleIdentifier(name string) bool {
	if name == "" {
		return false
	}
	for index, char := range name {
		if char >= 'a' && char <= 'z' || char >= 'A' && char <= 'Z' || char == '_' || char == '$' {
			continue
		}
		if index > 0 && char >= '0' && char <= '9' {
			continue
		}
		return false
	}
	return true
}

func splitIdentifier(name string) []string {
	parts := make([]string, 0, 3)
	current := &strings.Builder{}
	for _, char := range name {
		switch {
		case char >= 'a' && char <= 'z' || char >= 'A' && char <= 'Z' || char >= '0' && char <= '9':
			current.WriteRune(char)
		default:
			if current.Len() > 0 {
				parts = append(parts, strings.ToLower(current.String()))
				current.Reset()
			}
		}
	}
	if current.Len() > 0 {
		parts = append(parts, strings.ToLower(current.String()))
	}
	return parts
}