package storage

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strings"
)

// RecordCollectionProjection is the storage adapter input for creating and
// rebuilding a Collection's physical Records projection. Product field types
// remain strings here so this package does not depend on Backend Model.
type RecordCollectionProjection struct {
	ID      string
	Fields  []RecordProjectionField
	Indexes []RecordProjectionIndex
}

type RecordProjectionField struct {
	ID                  string
	Name                string
	Type                string
	Required            bool
	Unique              bool
	System              bool
	Default             json.RawMessage
	RelationCardinality string
}

type RecordProjectionIndex struct {
	ID     string
	Name   string
	Fields []string
	Unique bool
}

type UniqueConstraintValue struct {
	ColumnName   string
	DefaultField *RecordProjectionField
}

var sqliteIdentifierPattern = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// QuoteSQLiteIdentifier quotes only identifiers generated by Modelry. It
// rejects arbitrary names so request data cannot become SQL syntax.
func QuoteSQLiteIdentifier(identifier string) (string, error) {
	if !sqliteIdentifierPattern.MatchString(identifier) {
		return "", fmt.Errorf("unsafe SQLite projection identifier %q", identifier)
	}
	return `"` + identifier + `"`, nil
}

func RecordTableName(collectionID string) string {
	if !validProjectionID(collectionID, "col_") {
		return ""
	}
	return "mry_records_" + strings.TrimPrefix(collectionID, "col_")
}

func RecordFieldColumnName(fieldID, fieldName string, system bool) string {
	if system {
		return fieldName
	}
	if !validProjectionID(fieldID, "fld_") {
		return ""
	}
	return "mry_field_" + strings.TrimPrefix(fieldID, "fld_")
}

func validProjectionID(value, prefix string) bool {
	if !strings.HasPrefix(value, prefix) || len(value) != len(prefix)+32 {
		return false
	}
	for _, char := range value[len(prefix):] {
		if (char < '0' || char > '9') && (char < 'a' || char > 'f') {
			return false
		}
	}
	return true
}

func recordIndexName(collectionID, indexID string, uniqueField bool) string {
	if !validProjectionID(collectionID, "col_") {
		return ""
	}
	collectionKey := strings.TrimPrefix(collectionID, "col_")
	if uniqueField {
		if !validProjectionID(indexID, "fld_") {
			return ""
		}
		return "mry_unique_" + collectionKey + "_" + strings.TrimPrefix(indexID, "fld_")
	}
	if !validProjectionID(indexID, "idx_") {
		return ""
	}
	return "mry_index_" + collectionKey + "_" + strings.TrimPrefix(indexID, "idx_")
}

// CreateRecordProjection creates the initial physical Records table and its
// indexes within the caller's transaction.
func CreateRecordProjection(ctx context.Context, tx Executor, collection RecordCollectionProjection) error {
	tableName := RecordTableName(collection.ID)
	quotedTable, err := QuoteSQLiteIdentifier(tableName)
	if err != nil {
		return fmt.Errorf("build safe Collection record table: %w", err)
	}
	statement, err := createRecordTableStatement(tableName, collection)
	if err != nil {
		return err
	}
	if _, err := tx.ExecContext(ctx, statement); err != nil {
		return fmt.Errorf("create Collection record projection %s: %w", quotedTable, err)
	}
	return createRecordProjectionIndexes(ctx, tx, collection)
}

// RebuildRecordProjection replaces a Collection's physical Records table and
// copies compatible values in the same transaction as the caller's Apply.
func RebuildRecordProjection(ctx context.Context, tx Executor, previous, target RecordCollectionProjection) error {
	tableName := RecordTableName(target.ID)
	quotedTable, err := QuoteSQLiteIdentifier(tableName)
	if err != nil {
		return fmt.Errorf("build safe Collection record table: %w", err)
	}
	tempID, err := newProjectionID()
	if err != nil {
		return err
	}
	tempName := "mry_projection_" + tempID
	quotedTemp, err := QuoteSQLiteIdentifier(tempName)
	if err != nil {
		return fmt.Errorf("build safe temporary record table: %w", err)
	}
	createStatement, err := createRecordTableStatement(tempName, target)
	if err != nil {
		return err
	}
	if _, err := tx.ExecContext(ctx, createStatement); err != nil {
		return fmt.Errorf("prepare updated Collection record projection: %w", err)
	}

	insertColumns := []string{`"id"`, `"createdAt"`, `"updatedAt"`}
	selectExpressions := []string{`"id"`, `"createdAt"`, `"updatedAt"`}
	args := make([]any, 0)
	oldFields := make(map[string]RecordProjectionField, len(previous.Fields))
	for _, field := range previous.Fields {
		oldFields[field.ID] = field
	}
	for _, field := range target.Fields {
		if field.System {
			continue
		}
		columnName := RecordFieldColumnName(field.ID, field.Name, false)
		quotedColumn, err := QuoteSQLiteIdentifier(columnName)
		if err != nil {
			return fmt.Errorf("build safe Field projection column: %w", err)
		}
		insertColumns = append(insertColumns, quotedColumn)
		if _, existed := oldFields[field.ID]; existed {
			selectExpressions = append(selectExpressions, quotedColumn)
			continue
		}
		if len(field.Default) > 0 {
			var value any
			decoder := json.NewDecoder(strings.NewReader(string(field.Default)))
			decoder.UseNumber()
			if err := decoder.Decode(&value); err != nil {
				return fmt.Errorf("decode schema default for projection: %w", err)
			}
			value, err = databaseDefaultValue(field, value)
			if err != nil {
				return err
			}
			selectExpressions = append(selectExpressions, "?")
			args = append(args, value)
		} else {
			selectExpressions = append(selectExpressions, "NULL")
		}
	}
	oldTable, err := QuoteSQLiteIdentifier(RecordTableName(previous.ID))
	if err != nil {
		return fmt.Errorf("build safe prior record table: %w", err)
	}
	copySQL := fmt.Sprintf("INSERT INTO %s (%s) SELECT %s FROM %s", quotedTemp, strings.Join(insertColumns, ", "), strings.Join(selectExpressions, ", "), oldTable)
	if _, err := tx.ExecContext(ctx, copySQL, args...); err != nil {
		return fmt.Errorf("copy existing Records into updated schema: %w", err)
	}
	if _, err := tx.ExecContext(ctx, "DROP TABLE "+quotedTable); err != nil {
		return fmt.Errorf("replace prior Collection record projection: %w", err)
	}
	if _, err := tx.ExecContext(ctx, "ALTER TABLE "+quotedTemp+" RENAME TO "+quotedTable); err != nil {
		return fmt.Errorf("activate updated Collection record projection: %w", err)
	}
	return createRecordProjectionIndexes(ctx, tx, target)
}

func databaseDefaultValue(field RecordProjectionField, value any) (any, error) {
	if value == nil {
		return nil, nil
	}
	switch field.Type {
	case "json":
		encoded, err := json.Marshal(value)
		if err != nil {
			return nil, fmt.Errorf("encode JSON Field default: %w", err)
		}
		return string(encoded), nil
	case "relation":
		if field.RelationCardinality == "one-to-many" || field.RelationCardinality == "many-to-many" {
			encoded, err := json.Marshal(value)
			if err != nil {
				return nil, fmt.Errorf("encode Relation Field default: %w", err)
			}
			return string(encoded), nil
		}
	case "number":
		if number, ok := value.(json.Number); ok {
			parsed, err := number.Float64()
			if err != nil {
				return nil, fmt.Errorf("decode numeric Field default: %w", err)
			}
			return parsed, nil
		}
	}
	return value, nil
}

func createRecordTableStatement(tableName string, collection RecordCollectionProjection) (string, error) {
	quotedTable, err := QuoteSQLiteIdentifier(tableName)
	if err != nil {
		return "", err
	}
	columns := []string{`"id" TEXT PRIMARY KEY NOT NULL`, `"createdAt" TEXT NOT NULL`, `"updatedAt" TEXT NOT NULL`}
	for _, field := range collection.Fields {
		if field.System {
			continue
		}
		quotedColumn, err := QuoteSQLiteIdentifier(RecordFieldColumnName(field.ID, field.Name, false))
		if err != nil {
			return "", fmt.Errorf("build safe Field column: %w", err)
		}
		column := quotedColumn + " " + sqliteAffinity(field.Type)
		if field.Required {
			column += " NOT NULL"
		}
		columns = append(columns, column)
	}
	return "CREATE TABLE " + quotedTable + " (" + strings.Join(columns, ", ") + ")", nil
}

func sqliteAffinity(fieldType string) string {
	switch fieldType {
	case "number":
		return "NUMERIC"
	case "boolean":
		return "INTEGER"
	case "text", "dateTime", "json", "relation", "file":
		return "TEXT"
	default:
		return "BLOB"
	}
}

func createRecordProjectionIndexes(ctx context.Context, tx Executor, collection RecordCollectionProjection) error {
	for _, field := range collection.Fields {
		if field.System || !field.Unique {
			continue
		}
		indexID := recordIndexName(collection.ID, field.ID, true)
		quotedIndex, err := QuoteSQLiteIdentifier(indexID)
		if err != nil {
			return fmt.Errorf("build safe unique Field index: %w", err)
		}
		quotedTable, err := QuoteSQLiteIdentifier(RecordTableName(collection.ID))
		if err != nil {
			return err
		}
		quotedColumn, err := QuoteSQLiteIdentifier(RecordFieldColumnName(field.ID, field.Name, false))
		if err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx, "CREATE UNIQUE INDEX "+quotedIndex+" ON "+quotedTable+" ("+quotedColumn+")"); err != nil {
			return fmt.Errorf("project unique Field %q: %w", field.Name, err)
		}
	}
	for _, index := range collection.Indexes {
		indexID := recordIndexName(collection.ID, index.ID, false)
		quotedIndex, err := QuoteSQLiteIdentifier(indexID)
		if err != nil {
			return fmt.Errorf("build safe schema Index: %w", err)
		}
		quotedTable, err := QuoteSQLiteIdentifier(RecordTableName(collection.ID))
		if err != nil {
			return err
		}
		columns := make([]string, 0, len(index.Fields))
		for _, fieldID := range index.Fields {
			field, found := projectionFieldByID(collection.Fields, fieldID)
			if !found || field.System {
				return fmt.Errorf("Index %q refers to a missing Field", index.Name)
			}
			quotedColumn, err := QuoteSQLiteIdentifier(RecordFieldColumnName(field.ID, field.Name, false))
			if err != nil {
				return err
			}
			columns = append(columns, quotedColumn)
		}
		kind := "CREATE INDEX "
		if index.Unique {
			kind = "CREATE UNIQUE INDEX "
		}
		if _, err := tx.ExecContext(ctx, kind+quotedIndex+" ON "+quotedTable+" ("+strings.Join(columns, ", ")+")"); err != nil {
			return fmt.Errorf("project schema Index %q: %w", index.Name, err)
		}
	}
	return nil
}

func projectionFieldByID(fields []RecordProjectionField, id string) (RecordProjectionField, bool) {
	for _, field := range fields {
		if field.ID == id {
			return field, true
		}
	}
	return RecordProjectionField{}, false
}

func CountCollectionRecords(ctx context.Context, query Executor, collectionID string) (int64, error) {
	quotedTable, err := QuoteSQLiteIdentifier(RecordTableName(collectionID))
	if err != nil {
		return 0, err
	}
	var count int64
	if err := query.QueryRowContext(ctx, "SELECT COUNT(*) FROM "+quotedTable).Scan(&count); err != nil {
		return 0, fmt.Errorf("count Records in Collection: %w", err)
	}
	return count, nil
}

// VisitRecordFieldValues streams the current stored values for one projected
// Field and lets Backend Model validate them without knowing SQL identifiers.
func VisitRecordFieldValues(ctx context.Context, query Executor, collectionID, fieldID, fieldName string, system bool, visit func(any) (bool, error)) error {
	if visit == nil {
		return errors.New("record field value visitor is required")
	}
	table, err := QuoteSQLiteIdentifier(RecordTableName(collectionID))
	if err != nil {
		return err
	}
	column, err := QuoteSQLiteIdentifier(RecordFieldColumnName(fieldID, fieldName, system))
	if err != nil {
		return err
	}
	rows, err := query.QueryContext(ctx, "SELECT "+column+" FROM "+table)
	if err != nil {
		return fmt.Errorf("read projected Field values: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var raw any
		if err := rows.Scan(&raw); err != nil {
			return fmt.Errorf("scan projected Field value: %w", err)
		}
		continueReading, err := visit(raw)
		if err != nil {
			return err
		}
		if !continueReading {
			return nil
		}
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("finish reading projected Field values: %w", err)
	}
	return nil
}

// CountUniqueValueConflicts evaluates target unique constraints over the
// current projection. New fields contribute their pending defaults as bound
// values; existing fields use their generated physical columns.
func CountUniqueValueConflicts(ctx context.Context, query Executor, collectionID string, constraints [][]UniqueConstraintValue) (int64, error) {
	quotedTable, err := QuoteSQLiteIdentifier(RecordTableName(collectionID))
	if err != nil {
		return 0, err
	}
	var total int64
	for _, constraint := range constraints {
		selectExpressions := make([]string, 0, len(constraint))
		groups := make([]string, 0, len(constraint))
		nonNull := make([]string, 0, len(constraint))
		args := make([]any, 0, len(constraint))
		for index, value := range constraint {
			alias := fmt.Sprintf("k%d", index)
			if value.DefaultField == nil {
				quotedColumn, err := QuoteSQLiteIdentifier(value.ColumnName)
				if err != nil {
					return total, err
				}
				selectExpressions = append(selectExpressions, quotedColumn+" AS "+alias)
			} else {
				var defaultValue any
				if len(value.DefaultField.Default) > 0 {
					decoder := json.NewDecoder(strings.NewReader(string(value.DefaultField.Default)))
					decoder.UseNumber()
					if err := decoder.Decode(&defaultValue); err != nil {
						return total, fmt.Errorf("decode Field default for a unique constraint: %w", err)
					}
				}
				defaultValue, err = databaseDefaultValue(*value.DefaultField, defaultValue)
				if err != nil {
					return total, err
				}
				selectExpressions = append(selectExpressions, "? AS "+alias)
				args = append(args, defaultValue)
			}
			groups = append(groups, alias)
			nonNull = append(nonNull, alias+" IS NOT NULL")
		}
		statement := "SELECT COUNT(*) FROM (SELECT " + strings.Join(selectExpressions, ", ") + " FROM " + quotedTable + " GROUP BY " + strings.Join(groups, ", ") + " HAVING COUNT(*) > 1 AND " + strings.Join(nonNull, " AND ") + ")"
		var conflicts int64
		if err := query.QueryRowContext(ctx, statement, args...).Scan(&conflicts); err != nil {
			return total, fmt.Errorf("check pending unique constraints: %w", err)
		}
		total += conflicts
	}
	return total, nil
}

func RecordProjectionExists(ctx context.Context, query Executor, collectionID string) (bool, error) {
	var name string
	err := query.QueryRowContext(ctx, `SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?`, RecordTableName(collectionID)).Scan(&name)
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf("check Collection record projection: %w", err)
	}
	return name != "", nil
}

func newProjectionID() (string, error) {
	var value [16]byte
	if _, err := rand.Read(value[:]); err != nil {
		return "", fmt.Errorf("generate temporary record projection ID: %w", err)
	}
	return hex.EncodeToString(value[:]), nil
}
